title: Juice Landing Page
author: Mike JS. Choi
email: mkchoi212@icloud.com
description: >-
  ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks feature. 
  This theme provides a set of page-level components and a pre-configured Forestry Blocks UI 
  that will empower content editors to construct their own webpages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deadbeef.me" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

