title: Juice Landing Page
author: Mike JS. Choi
email: mkchoi212@icloud.com
description: >-
  The missing Bluetooth manager for macOS.
baseurl: "/Juice" # the subpath of your site, e.g. /blog
url: "https://deadbeef.me" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

